[package]
name = "piet-dx12"
version = "0.1.0"
authors = ["bhmerchant@gmail.com <bhmerchant@gmail.com>"]
edition = "2018"

[dependencies]
winapi = "0.3.*"
user32-sys = "0.3.*"
kernel32-sys = "0.3.*"

